name: Build Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies as well as project-specific tools
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration ${{ matrix.configuration }} --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Install Snyk
        run: |
          sudo npm install -g snyk

      - name: Authenticate Snyk
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk auth $SNYK_TOKEN

      - name: Run Snyk Open Source (SCA) on all projects
        run: |
          for csproj in $(find . -name "*.csproj"); do
            echo "Testing $csproj"
            snyk test --file=$csproj --package-manager=nuget || true
          done

      - name: Create Snyk Open Source (SCA) snapshot for all projects
        run: |
          for csproj in $(find . -name "*.csproj"); do
            echo "Monitoring $csproj"
            snyk monitor --file=$csproj --package-manager=nuget || true
          done

